export default {
  main: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  travellerCardsWrapper: {
    marginTop: 20,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  cardWrapper: {
    boxShadow: 'rgba(0, 0, 0, 0.5) 3px 3px 6px -5px',
    border: '1px solid #e9e4e4',
    borderRadius: '8px',
    width: '90%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 8,
    margin: 8,
    backgroundColor: 'white',
  },
  imgWrapper: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 3,
    justifyContent: 'space-between',
  },
  img: {
    width: 50,
    height: 50,
    borderRadius: '50%',
    objectFit: 'cover',
  },
  statusCard: {
    position: 'absolute',
    bottom: 4,
    left: 38,
    fontSize: 12,
    fontWeight: 'bold',
    padding: 2,
    borderRadius: 4,
    color: 'white',
  },
};
